CREATE TABLE equipe (
    id SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    nom VARCHAR(30) UNIQUE NOT NULL,
    quartier VARCHAR(50),
    nbVictoires SMALLINT UNSIGNED DEFAULT 0
);

CREATE TABLE joueur (
    id SMALLINT UNSIGNED AUTO_INCREMENT,
    prenom VARCHAR(50) NOT NULL,
    nom VARCHAR(50) NOT NULL,
    idEquipe SMALLINT UNSIGNED NOT NULL, -- NULL si on choisi ON DELETE SET NULL
    FOREIGN KEY(idEquipe) REFERENCES equipe(id) ON DELETE CASCADE, --ON DELETE SET NULL
    PRIMARY KEY(id)
);